### PR TITLE
- update ThreadSleep accuracy

### PR DESCRIPTION
**Pull request by jowenece**
We were seeing highly inaccruate sleep times in several environements.  On some server up to 3x more sleep time than specificied.  This helps improve accuracy based on time calculations instead of number of steps.

### CODE REVIEW

**Comment by eben-roux** [comment]
Thanks for the PR.

Are you in a hurry to get this in, or are you OK with using your source for now?

The reason I ask is that I'm in the middle of quite chunk of refactoring that I'd like to get out of the way.

**Comment by jowenece** [comment]
No rush.  Thanks.

**Comment by eben-roux** [comment]
Hi,

Just to let you know: I haven't forgotten about this... I'm just still busy on the refactoring and it it taking some time since I can't get around to everything :)

**Comment by eben-roux** [comment]
Still haven't forgotten... making progress with the changes.

**Pull request merged**
